version: '3.1'

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    env_file:
      - .env
  redis:
    image: redis
    restart: always
    command: /bin/sh -c "redis-server --save 60 1 --requirepass $$REDIS_HOST_PASSWORD"
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
volumes:
  mongodb:
  redis:
