ingress:
  hosts:
    - host: api.intelli-mate.xgeeks.tech
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.intelli-mate.xgeeks.tech
      secretName: intelli-mate-api-tls

extraVolumeMounts:
  - name: documents
    mountPath: /app/api/documents
    size: 5Gi
