ingress:
  hosts:
    - host: api.intelli-mate.xgeeks.tech
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.intelli-mate.xgeeks.tech
      secretName: intelli-mate-api-tls

persistence:
  enabled: true
  name: documents
  storageClass: default
  size: 5Gi
  mountPath: /app/api/documents
