apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intelli-mate-web-ui.fullname" . }}
  labels:
    {{- include "intelli-mate-web-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "intelli-mate-web-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "intelli-mate-web-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "intelli-mate-web-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            {{- if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ .Values.configmap.name | default (include "intelli-mate-web-ui.fullname" .) | quote }}
            {{- end }}
            {{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ .Values.secret.name | default (include "intelli-mate-web-ui.fullname" .) | quote }}
            {{- end }}
          {{- if .Values.healthcheck.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.readiness.delay }}
            periodSeconds: {{ .Values.healthcheck.readiness.period }}
            failureThreshold: {{ .Values.healthcheck.readiness.failure }}
          {{- end }}
          {{- if .Values.healthcheck.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.liveness.delay }}
            periodSeconds: {{ .Values.healthcheck.liveness.period }}
            failureThreshold: {{ .Values.healthcheck.liveness.failure }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
