{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intelli-mate-web-ui.fullname" . }}
  labels:
    {{- include "intelli-mate-web-ui.labels" . | nindent 4 }}
type: Opaque
data:
  FOO: {{ "BAR" | b64enc | quote }}
{{- end }}
